file_format: "1"
id: lily58
name: Lily58
type: shield
url: https://github.com/SimonHawk
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - HawkV0_left
  - HawkV0_right
