file_format: "1"
id: hawkV0
name: HawkV0
type: shield
url: https://github.com/SimonHawk
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - studio
siblings:
  - HawkV0_left
  - HawkV0_right
